apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: assisted-installer-vxg8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: assisted-installer-vxg8
    app.kubernetes.io/part-of: assisted-installer
  name: assisted-installer-vxg8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: assisted-installer-vxg8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: assisted-installer-vxg8
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/assisted-installer/assisted-installer-vxg8@sha256:06243e40ffaac733008f8f3567acd001811d716f4d8fdfaccea63f78a02e3c96
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
